### ISSUE TITLE
Encrypt throws error when using imported key

### ISSUE THREAD

**Issue by NeonPaul** [cisco/node-jose#162]
When I try to use an imported key to encrypt a string, an error is thrown:

```js
const jose = require('node-jose');

(async () => {
  const keystore = jose.JWK.createKeyStore();

  let key = await keystore.generate("oct", 256);

  // Simulate export & re-import of key
  key = await jose.JWK.asKey(JSON.parse(JSON.stringify(key)));

  const enc = await jose.JWE.createEncrypt(key).update('hello world').final();
  console.log(enc);
})();
  ```
If I use the generated key directly it works.

The specific error and call stack is:
```
TypeError: Cannot read property 'indexOf' of undefined
    at procR (node_modules/node-jose/lib/jwe/encrypt.js:184:25)
    at node_modules/node-jose/lib/jwe/encrypt.js:278:20
    at Array.map (<anonymous>)
    at node_modules/node-jose/lib/jwe/encrypt.js:277:25
    at <anonymous>
```

I'm using node version 8.9.1.

**Comment by panva** [comment]
This works.
```js
const jose = require('node-jose');

(async () => {
  const keystore = jose.JWK.createKeyStore();

  let key = await keystore.generate("oct", 256);

  // Simulate export & re-import of key
  key = await jose.JWK.asKey(JSON.parse(JSON.stringify(key.toJSON(true))));

  const enc = await jose.JWE.createEncrypt(key).update('hello world').final();
  console.log(enc);
})();
```
the problem is you're not serializing the key according to the doc

To export the public portion of a Key as a JWK:
```js
var output = key.toJSON();
```
To export the public and private portions of a Key:

```js
var output = key.toJSON(true);
```

**Comment by NeonPaul** [comment]
@panva Ah thanks! My apologies for not reading the docs close enough
