### ISSUE TITLE
JWE data is more than 256 bytes

### ISSUE THREAD

**Issue by vinaypandey82** [cisco/node-jose#172]
Hi
I am working on a task to generate JWE using public key and decrypt at server side using the private key. Below is my code

```
var jose =  require('node-jose');
var payload = '{"cardNumber":"4029739658517984", "expirationMonth":"04", "cardholderName":"Test Name", "expirationYear":"2019"}';

const webkey = {
    "keys": [
        {
            "kty": "RSA",
            "e": "MTAwMDE=",
            "alg":"RSA-OAEP-256",
            "n": "‌c2494f356725cbe7239501d4b9ceca19ad2cd6aeff0d104e4dba3dba6e55ef1d9e9c08c261dfa21266ca1ba96a713c0efea0fff9a179cfd147ca674b02d1e4b2a1cf647e20ef087d66b2ad7090aab1bb001dfd32f80f777a894804e5f88e66542a1fa69ea629faf8d539a2e49131b126f796be3011738cd553ff825ee1de829a9515e7c4384093f6b672de650577860febb45eebe8625c4de422cca00fac681a364ba79157d7d8e9f84b140664f67a95533dd7077fde40e3e07bac0d6fa9abb211d9162e2f13a4536907b42e6d987a2ae4084e94fb36e8ee1a91615d3cc6a2985dce5810a831d312872d6647ff4956dd12f878a785121a0b5d244f73a9b7177f"
        }
    ]
};


//generate key store from public JWK
jose.JWK.asKeyStore(webkey).
then((result) => {
    console.log("Key Store File", JSON.stringify(result.toJSON()));
    let keyStore = result;

    //get the key to encrypt
    const encryptionKey = keyStore.get(webkey.keys[0].kid);
    // console.log("Encryption Key", JSON.stringify(encryptionKey));
    const output = jose.util.base64url.encode(JSON.stringify(payload));
    const input = jose.util.asBuffer(output);

    //encrypting content
    jose.JWE.createEncrypt({ format: 'compact',contentAlg : "A128GCM",alg: 'RSA_OAEP-256',enc:'128GCM'}, encryptionKey).
    update(input).
    final().
    then((result) => {
        console.log("Encryption result", JSON.stringify(result));

    }, (error) => {
        console.log("Error2", error.message)
    });

}, (error) => {
    console.log("error1", error.message);
})
```

Now at the server side I am using the Jose RSADecrypter(Java code) to decrypt the JWE
```

JWEObject jweObject = JWEObject.parse(jweString);
                RSADecrypter decrypter = new RSADecrypter(privateKey);
                jweObject.decrypt(decrypter); 
```

 and getting error 
```

Caused by: javax.crypto.IllegalBlockSizeException: Data must not be longer than 256 bytes
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:344)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
```

I am not able to understand why I am getting more than 256 bytes of data and how can I reduce the size. I tried every possible method but size is still more than 256 bytes. I debug the server side code and found it to be 382 bytes. Is it a bug in the node-jose? if not please let me know what's wrong in my code.

**Comment by linuxwolf** [comment]
Looking at `webkey`, I noticed the embedded key's `n` is odd; it appears to only contain characters in the hex encoding alphabet (which happens to be a subset of the URL-safe base64 alphabet).  It also is 382 bytes long once "base64url" decoded, rather than "hex" (where it comes out to 256 bytes, or 2048 bits).

This might explain your issue.  JWK binary properties (e.g., "e", "n", etc) **MUST** be URL-safe base64 encoded, and not hex encoded.  With that, I'm guessing `webkeys`  should actually be:

```
const webkey = {
    "keys": [
        {
            "kty": "RSA",
            "e": "MTAwMDE=",
            "alg":"RSA-OAEP-256",
            "n": "‌wklPNWcly-cjlQHUuc7KGa0s1q7_DRBOTbo9um5V7x2enAjCYd-iEmbKG6lqcTwO_qD_-aF5z9FHymdLAtHksqHPZH4g7wh9ZrKtcJCqsbsAHf0y-A93eolIBOX4jmZUKh-mnqYp-vjVOaLkkTGxJveWvjARc4zVU_-CXuHegpqVFefEOECT9rZy3mUFd4YP67Re6-hiXE3kIsygD6xoGjZLp5FX19jp-EsUBmT2epVTPdcHf95A4-B7rA1vqauyEdkWLi8TpFNpB7QubZh6KuQITpT7NujuGpFhXTzGophdzlgQqDHTEoctZkf_SVbdEvh4p4USGgtdJE9zqbcXfw"
        }
    ]
};
```

**Comment by vinaypandey82** [comment]
Thanks for quick reply. I am using NodeRSA to create JWK which gives me BigInteger for modulus. I am not very familiar with node-js, can you please let me know how can I generate url-safe base64 encoded modulus from my public key? I tried so many ways but not able to get the desired output.

**Comment by linuxwolf** [comment]
There are no explicit tests for encrypting/decrypting using `RSA-OAEP-256`, although there are for `RSA-OAEP`.  I just tried a sample data set against an independent implementation ([jose](https://github.com/latchset/jose)) and successfully decrypted a message encrypted with node-jose.

At this point, I don't believe the error is in node-jose.  It might be in the version of Numbus-JOSE+JWT you are using, or in your code.

**Comment by vinaypandey82** [comment]
Thanks for all the help you provided @linuxwolf . It worked after changing the algorithm to RSA-OAEP.

**Comment by vinaypandey82** [comment]
Hi @linuxwolf 
Sorry to open this issue after closing it, actually it didn't work last time after changing the algo to RSA-OAEP, but I thought it worked. But I am struggling to decrypt the JWE created using node-js in Java. I could see that JWE I have has padding in it. I am not sure what could be the problem.
Following is my JS code:
`var payload = '{"hello world"}';
const output = jose.util.base64url.encode(payload);
const input = jose.util.asBuffer(output);
jose.JWE.createEncrypt({ format: 'compact', "contentAlg":"A256GCM" , fields: {
        alg: "RSA-OAEP",
        enc: "A256GCM"
    }},{"kty":"RSA","n": "‌ldf2h7Vq3yzbeAUdjQYcNXrnVl96y3gJYkEDTy3_wVOfAa-E0c5FqartDWxf7YGQQf-jKVV5MXDpahKwg2MWov4p8Fyxe8kLSCxDKRpHoNemcmMybZ_GP2VhvgssbkAxVzG7BS2r5p94CmiUpHLbiq7njrDNlmZABiQ2E8KCYxG9AlUfdtyAYnKWNGyr6MeEGdvcbvsKzhUDf6r3DEBrQqfd2qUM2aACm1vq2ovhOhYsKuyI3c6oX18Wv4M6JBNZwNNkHITyv3hmGFP2K-F6lcooHEPHxUc3_5lO6eU3Nt_MKtkV3YjV8Vv5QkroLfJioV9DTg-mPDS8-uOnL95ARQ",
    "e": "AQAB"}).
    update(input,"utf8").
    final().
    then((result) => {
        console.log("Encryption result", result);
    }, (error) => {
        console.log("Error2", error.message)
    });`

and below is the error I am getting server side:
`com.nimbusds.jose.JOSEException: Decryption error
	at com.nimbusds.jose.crypto.RSA_OAEP.decryptCEK(RSA_OAEP.java:108)
	at com.nimbusds.jose.crypto.RSADecrypter.decrypt(RSADecrypter.java:238)
	at com.nimbusds.jose.JWEObject.decrypt(JWEObject.java:415)
	at com.cts.directpay.DecryptionTest.main(DecryptionTest.java:68)
Caused by: javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadOAEP(RSAPadding.java:499)
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:293)
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at com.nimbusds.jose.crypto.RSA_OAEP.decryptCEK(RSA_OAEP.java:100)
	... 3 more`

**Comment by linuxwolf** [comment]
@vinaypandey82 

The key you've provided here:
```json
{
    "kty": "RSA",
    "n": "‌ldf2h7Vq3yzbeAUdjQYcNXrnVl96y3gJYkEDTy3_wVOfAa-E0c5FqartDWxf7YGQQf-jKVV5MXDpahKwg2MWov4p8Fyxe8kLSCxDKRpHoNemcmMybZ_GP2VhvgssbkAxVzG7BS2r5p94CmiUpHLbiq7njrDNlmZABiQ2E8KCYxG9AlUfdtyAYnKWNGyr6MeEGdvcbvsKzhUDf6r3DEBrQqfd2qUM2aACm1vq2ovhOhYsKuyI3c6oX18Wv4M6JBNZwNNkHITyv3hmGFP2K-F6lcooHEPHxUc3_5lO6eU3Nt_MKtkV3YjV8Vv5QkroLfJioV9DTg-mPDS8-uOnL95ARQ",
    "e": "AQAB"
}
```
Still has a bad length, I think:

```javascript
$ key.length
2040
```

How exactly are you generating/obtaining the JWK form of your RSA key?

**Comment by vinaypandey82** [comment]
I am getting modulus from server. I don't see any good way to get expoent and modulus in Javascript so I am doing it in Java. Below is the code to get modulus and exponent.

```
String pub = "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbGRmMmg3VnEzeXpiZUFVZGpRWWMNCk5Ycm5WbDk2eTNnSllrRURUeTMvd1ZPZkFhK0UwYzVGcWFydERXeGY3WUdRUWYraktWVjVNWERwYWhLd2cyTVcNCm92NHA4Rnl4ZThrTFNDeERLUnBIb05lbWNtTXliWi9HUDJWaHZnc3Nia0F4VnpHN0JTMnI1cDk0Q21pVXBITGINCmlxN25qckRObG1aQUJpUTJFOEtDWXhHOUFsVWZkdHlBWW5LV05HeXI2TWVFR2R2Y2J2c0t6aFVEZjZyM0RFQnINClFxZmQycVVNMmFBQ20xdnEyb3ZoT2hZc0t1eUkzYzZvWDE4V3Y0TTZKQk5ad05Oa0hJVHl2M2htR0ZQMksrRjYNCmxjb29IRVBIeFVjMy81bE82ZVUzTnQvTUt0a1YzWWpWOFZ2NVFrcm9MZkppb1Y5RFRnK21QRFM4K3VPbkw5NUENClJRSURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0=";
			String reconstructedPublicKeyString = new String(
					Base64.decodeBase64(pub.getBytes()));
			PemReader pemReader = new PemReader(new StringReader(
					reconstructedPublicKeyString));
			PemObject pemObject = pemReader.readPemObject();
			pemReader.close();
			byte[] content = pemObject.getContent();
			X509EncodedKeySpec pubKeySpec = new X509EncodedKeySpec(content);
			KeyFactory factory = KeyFactory.getInstance("RSA", "BC");
			RSAPublicKey reconstructedPublicKey = (RSAPublicKey) factory
					.generatePublic(pubKeySpec);

                        String modulus = Base64URL.encode(reconstructedPublicKey.getModulus();
			String exponent = Base64URL.encode(reconstructedPublicKey.getPublicExponent())
```

**Comment by linuxwolf** [comment]
I think the issue is the exported key is missing a leading bit somehow, but I'm not sure.  I'm not that familiar with the Java implementations to know off-hand.

I **STRONGLY** recommend you not perform this kind of export by hand.

* It appears from other replies you are using `nimbus-jose-jwt`; it transforming an RSAPublicKey instance into a JWK (at first glance, [`java.secrity.interfaces.RSAPublicKey` -> `com.nimbusds.jose.jwk.RSAKey` using a builder](http://static.javadoc.io/com.nimbusds/nimbus-jose-jwt/5.9/com/nimbusds/jose/jwk/RSAKey.Builder.html) then [`com.nimbusds.jose.jwk.RSAKey` -> JSON ](http://static.javadoc.io/com.nimbusds/nimbus-jose-jwt/5.9/com/nimbusds/jose/jwk/RSAKey.html#toJSONObject--)).
* It should also be possible to export the PEM-encoded public key (either as a X509 certificate or SPKI raw public key) and import it into node-jose using [`jose.JWK.asKey(pemKey, "pem")`](https://github.com/cisco/node-jose#importing-and-exporting-a-single-key).
